name: Mark stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
  - cron: "00 6 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Never close stale issues
        days-before-close: -1,
        # Only label issues, no commenting.
        skip-stale-pr-message: true,
        skip-stale-issue-message: true,  
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
